### ISSUE TITLE
Implement some additional `payments` methods

### ISSUE THREAD

**Issue by eruizgar91** [nevermined-io/payments#14]
**DEPENDS OF ZERODEV 5 and VIEM**

Support latest methods that the cli contains into the library and in nvm-backend

```[tasklist]
### Tasks
- [x] Show
- [x] Balance  (credits/time)
- [x] Update Session Keys behavior
- [x] Order
- [ ] Download
- [x] Update the documentation
```
